### ISSUE TITLE
How to adapt the tooltip of the demo to the size of the text it contains?

### ISSUE THREAD

**Issue by nico75005** [Jawbone/JBChartView#145]
Hi,

I use JBChartView for data that might be like "1.2" or "1.2349353" or even longer. How can I adapt the size of the tooltip to those value?

Thanks

**Comment by terryworona** [comment]
The tooltip's text should adjust accordingly. See screenshot. 

Is this what you mean?
![screen shot 2015-03-30 at 3 42 35 pm](https://cloud.githubusercontent.com/assets/358709/6908660/7bae38f6-d6f3-11e4-9e4e-8829aefdceae.png)

**Comment by nico75005** [comment]
Actually if I'm not wrong, it's the size of the text that adapts itself accordingly to the size of the tooltip's frame. The longest the text is, the smallest it will be. I would like to adapt the tooltip's frame to its content. Like if I have something like "Good evening my name is Nico", the size of the text will stay the same and it will be the frame of the tooltip that will be bigger. Is it possible?

**Comment by terryworona** [comment]
Anything is possible :)

Because this is a demo project, and the tooltip is technically not part of the actual library (just an example of how you can use didSelect* callbacks), I won't be making any modifications to it. 

If you want to make it adapt to any size, the following steps should set you in the right direction:

1. Implement sizeThatFits in the tooltip class that returns the width and height of the frame according to the text contained within it. 
2. Call sizeThatFits on the tooltip instance any time you change it's content. 
3. Profit.

The same pattern works for any custom UIView with dynamic content.

**Comment by nico75005** [comment]
I'm trying your way only now but it doesn't work on your demo (well at least I didn't manage to make it work). I did the following: 

Set `_textLabel.adjustsFontSizeToFitWidth = NO;` in `JBChartTooltipView`
Add `- (CGSize)sizeThatFits:(CGSize)size 
{
	return size;
}` in `JBChartTooltipView`
Call `[self.tooltipView sizeThatFits: CGSizeMake(200, 200)];`in `dispatch_block_t adjustTooltipPosition` in `JBBaseChartViewController`

And the tooltip doesn't get bigger. I followed all your steps, I don't understand why it doesn't work. If you have any idea that would be great.

Thanks anyway :)

**Comment by terryworona** [comment]
sizeThatFits shouldn't return size, it should return a dynamic CGSize based on the contents of your view. 

Then call sizeToFit, not sizeThatFits (this won't do anything but return a size). 

To test it (hardcoded):

1. Add - (CGSize)sizeThatFits:(CGSize)size { return CGSizeMake(200, 200); }
2. Call [self.tooltipView sizeToFit];

**Comment by nico75005** [comment]
Yes indeed, with the correct call to sizeToFit it works fine. Thanks a lot!
