### ISSUE TITLE
Footer and Header view Swift implementation

### ISSUE THREAD

**Issue by kutyel** [Jawbone/JBChartView#152]
Is there a Swift implementation for the **JBBarChartFooterView** and **JBChartHeaderView** shown at the demo project?

```swift
    let chartFooter = UIView(frame: CGRectMake(anualReportChartPadding, ceil(self.view.bounds.size.height * 0.5) - ceil(anualReportChartFooterHeight * 0.5), self.view.bounds.size.width - (anualReportChartPadding * 2), anualReportChartFooterHeight))
    chartFooter.padding = anualReportChartFooterPadding;
    chartFooter.leftLabel.text = monthSymbols.first().uppercaseString
    chartFooter.leftLabel.textColor = UIColor.lightGrayColor()
    chartFooter.rightLabel.text = monthSymbols.last().uppercaseString
    chartFooter.rightLabel.textColor = UIColor.lightGrayColor()
    anualReportsChart.footerView = chartFooter
```

This shows an error on xcode, as natural, cause there is no class or interface implementation.

Thanks in advance!

**Comment by terryworona** [comment]
What is the exact error?

**Comment by kutyel** [comment]
It says something like "no padding definition for UIView". It is because I am using the library in my swift project but have not included the mentioned files, as they are Objective-C. Just wondering if there is some swift implementation already or that I have to make one for my own.

**Comment by terryworona** [comment]
can please post the complete compile error....

**Comment by kutyel** [comment]
```swift
Swift Compiler Error
'UIView' does not have a member named 'padding'
Swift Compiler Error
'UIView' does not have a member named 'leftLabel'
Swift Compiler Error
'UIView' does not have a member named 'leftLabel'
Swift Compiler Error
'UIView' does not have a member named 'rightLabel'
Swift Compiler Error
'UIView' does not have a member named 'rightLabel'
```

**Comment by terryworona** [comment]
This compile error has nothing to do with swift. 

It's because your instantiating a UIView instance. UIView's don't have padding, leftLabel or rightLabel properties. 

These properties are part of the JBFooterViews (ie. JBLineChartFooterView and JBBarChartFooterView). These views are _not_ part of the JBChartView core library - they were included in the demo project to show how the chart can support a custom UIView footer (or header). 

Please create your own footer or header instances with whatever properties you want. Closing as not an issue.
