### ISSUE TITLE
Bar chart doesn't paint inside selected UITableViewCell

### ISSUE THREAD

**Issue by williamsjj** [Jawbone/JBChartView#214]
Been banging my head on this for a few days...paints fine when UITableViewCell is unselected:

![graph_painting_unselected](https://cloud.githubusercontent.com/assets/119410/17119089/b5dd0b54-5278-11e6-98ab-e95b1824157f.png)

However, as long as the cell is selected, the JBBarChartView disappears...every other part of the cell's contentView paints fine (including the chart's footerView):
![graph_notpainting_onselect](https://cloud.githubusercontent.com/assets/119410/17119107/d8efbbfa-5278-11e6-9db5-156e7f7509b8.png)

```
init(style: UITableViewCellStyle, reuseIdentifier: String?, parentVC:ManageHistoryVC?) {
    self.activitySparkChart = JBBarChartView();
    self.activitySparkChartFooterVC = ActivityChartFooterViewController(parentChart:self.activitySparkChart);
    self.activitySparkChart.translatesAutoresizingMaskIntoConstraints = false;
...
    self.activitySparkChart.footerView = self.activitySparkChartFooterVC.view;
    self.activitySparkChartFooterVC.updateAxis(left: "", center: "", right: "");
    self.contentView.addSubview(self.activitySparkChart);
```

```
override func layoutSubviews() {
        super.layoutSubviews();
        
        self.activitySparkChartFooterVC.viewWillLayoutSubviews();
        self.activitySparkChart.reloadDataAnimated(true);
    }
```

Any thoughts on what might be causing this would be greatly appreciated. I've also tried forcing a reloadData of the chart inside of the UITableViewCell's ```setSelected``` and ```setHighlighted```, to no avail.

**Comment by terryworona** [comment]
We encountered this issue when we wrote our demo project "Spark Friends". Link [here](https://github.com/Jawbone/spark-friends-ios). 

It happens because the table view cell automatically changes background color of all views inside content view for highlighted state. 

There's a slew of solutions to the problem. Full stack thread [here](http://stackoverflow.com/questions/6745919/uitableviewcell-subview-disappears-when-cell-is-selected). 

I recommend turning off cell selections (ie. UITableViewCellSelectionStyleNone) and overriding `setHighlighted:animated:` and/or `setSelected:animated:` to set the background of the cell manually. 

It's a huge annoyance! Closing for now. Please defer questions to the stack thread if you can't fix it, or re-open if you really thing it's limited to JBChartView.

**Comment by williamsjj** [comment]
Thanks Terry, I really appreciate it. I saw that StackOverflow thread but it was so focused on the background color not changing I didn't think it would apply to repainting of the contentView. But you're right, handling it by hand in setSelected/setHighlighted fixes the repainting issue.
